version: "2"
services:
  backend:
    image: 'opencvcourses/opencv-docker:4.5.1'
    volumes: 
      - ./backend:/app
    working_dir: /app
    command: /app/bin/start.sh
    ports: 
      - '5000:5000'
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "5000"
  frontend:
    image: 'node:14-alpine'
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: /app/bin/start.sh
    ports:
      - '8000:8000'
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
